package sipresdik.view;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
import sipresdik.dao.DasboardDao;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.Map;
import javax.swing.SwingUtilities;


/**
 *
 * @author HP
 */
public class Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("FlatLaf Error");
        }
        initComponents();
        loadData();
    }
    
    

    private void loadData() {
        DasboardDao ds = new DasboardDao();
        try {
            
            int total = ds.totalGuru();
            int hadir = ds.hadir();
            int tidak = ds.tidakHadir();

          
            Dtotalguru.setText(String.valueOf(total));
            Dhadir.setText(String.valueOf(hadir));
            Dtidakhadir.setText(String.valueOf(tidak));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "Gagal mengambil data dashboard:\n" + ex.getMessage(),
                    "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barAtas = new javax.swing.JPanel();
        lbDashboard = new javax.swing.JLabel();
        pnDasar = new javax.swing.JPanel();
        pnDasarTotalGuru = new javax.swing.JPanel();
        barAtasTotalGuru = new javax.swing.JPanel();
        lbTotalGuru = new javax.swing.JLabel();
        pnUtamaTotalGuru = new javax.swing.JPanel();
        Dtotalguru = new javax.swing.JLabel();
        pnDasarTidakHadir = new javax.swing.JPanel();
        barAtasTidakHadir = new javax.swing.JPanel();
        barTidakHadir = new javax.swing.JLabel();
        pnUtamaTidakHadir = new javax.swing.JPanel();
        Dtidakhadir = new javax.swing.JLabel();
        pnDasarHadir = new javax.swing.JPanel();
        barAtasHadir = new javax.swing.JPanel();
        lbHadir = new javax.swing.JLabel();
        pnUtamaHadir = new javax.swing.JPanel();
        Dhadir = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        barAtas.setBackground(new java.awt.Color(16, 185, 129));

        lbDashboard.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        lbDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lbDashboard.setText("Dashboard");

        javax.swing.GroupLayout barAtasLayout = new javax.swing.GroupLayout(barAtas);
        barAtas.setLayout(barAtasLayout);
        barAtasLayout.setHorizontalGroup(
            barAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barAtasLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lbDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(519, Short.MAX_VALUE))
        );
        barAtasLayout.setVerticalGroup(
            barAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(barAtas, java.awt.BorderLayout.PAGE_START);

        pnDasarTotalGuru.setBackground(new java.awt.Color(255, 255, 255));
        pnDasarTotalGuru.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 185, 129)));
        pnDasarTotalGuru.setLayout(new java.awt.BorderLayout());

        barAtasTotalGuru.setBackground(new java.awt.Color(16, 185, 129));

        lbTotalGuru.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTotalGuru.setForeground(new java.awt.Color(255, 255, 255));
        lbTotalGuru.setText("Total Guru");

        javax.swing.GroupLayout barAtasTotalGuruLayout = new javax.swing.GroupLayout(barAtasTotalGuru);
        barAtasTotalGuru.setLayout(barAtasTotalGuruLayout);
        barAtasTotalGuruLayout.setHorizontalGroup(
            barAtasTotalGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barAtasTotalGuruLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lbTotalGuru)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        barAtasTotalGuruLayout.setVerticalGroup(
            barAtasTotalGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTotalGuru, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        pnDasarTotalGuru.add(barAtasTotalGuru, java.awt.BorderLayout.PAGE_START);

        pnUtamaTotalGuru.setBackground(new java.awt.Color(255, 255, 255));

        Dtotalguru.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Dtotalguru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dtotalguru.setText("15");

        javax.swing.GroupLayout pnUtamaTotalGuruLayout = new javax.swing.GroupLayout(pnUtamaTotalGuru);
        pnUtamaTotalGuru.setLayout(pnUtamaTotalGuruLayout);
        pnUtamaTotalGuruLayout.setHorizontalGroup(
            pnUtamaTotalGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnUtamaTotalGuruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dtotalguru, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnUtamaTotalGuruLayout.setVerticalGroup(
            pnUtamaTotalGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUtamaTotalGuruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dtotalguru, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnDasarTotalGuru.add(pnUtamaTotalGuru, java.awt.BorderLayout.CENTER);

        pnDasarTidakHadir.setBackground(new java.awt.Color(255, 255, 255));
        pnDasarTidakHadir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 185, 129)));
        pnDasarTidakHadir.setLayout(new java.awt.BorderLayout());

        barAtasTidakHadir.setBackground(new java.awt.Color(16, 185, 129));

        barTidakHadir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        barTidakHadir.setForeground(new java.awt.Color(255, 255, 255));
        barTidakHadir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barTidakHadir.setText("Tidak Hadir");

        javax.swing.GroupLayout barAtasTidakHadirLayout = new javax.swing.GroupLayout(barAtasTidakHadir);
        barAtasTidakHadir.setLayout(barAtasTidakHadirLayout);
        barAtasTidakHadirLayout.setHorizontalGroup(
            barAtasTidakHadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barAtasTidakHadirLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(barTidakHadir, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        barAtasTidakHadirLayout.setVerticalGroup(
            barAtasTidakHadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barTidakHadir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        pnDasarTidakHadir.add(barAtasTidakHadir, java.awt.BorderLayout.PAGE_START);

        pnUtamaTidakHadir.setBackground(new java.awt.Color(255, 255, 255));

        Dtidakhadir.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Dtidakhadir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dtidakhadir.setText("5");

        javax.swing.GroupLayout pnUtamaTidakHadirLayout = new javax.swing.GroupLayout(pnUtamaTidakHadir);
        pnUtamaTidakHadir.setLayout(pnUtamaTidakHadirLayout);
        pnUtamaTidakHadirLayout.setHorizontalGroup(
            pnUtamaTidakHadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnUtamaTidakHadirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dtidakhadir, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnUtamaTidakHadirLayout.setVerticalGroup(
            pnUtamaTidakHadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUtamaTidakHadirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dtidakhadir, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnDasarTidakHadir.add(pnUtamaTidakHadir, java.awt.BorderLayout.CENTER);

        pnDasarHadir.setBackground(new java.awt.Color(255, 255, 255));
        pnDasarHadir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 185, 129)));
        pnDasarHadir.setLayout(new java.awt.BorderLayout());

        barAtasHadir.setBackground(new java.awt.Color(16, 185, 129));

        lbHadir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbHadir.setForeground(new java.awt.Color(255, 255, 255));
        lbHadir.setText(" Hadir Hari Ini");

        javax.swing.GroupLayout barAtasHadirLayout = new javax.swing.GroupLayout(barAtasHadir);
        barAtasHadir.setLayout(barAtasHadirLayout);
        barAtasHadirLayout.setHorizontalGroup(
            barAtasHadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barAtasHadirLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbHadir)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        barAtasHadirLayout.setVerticalGroup(
            barAtasHadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbHadir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        pnDasarHadir.add(barAtasHadir, java.awt.BorderLayout.PAGE_START);

        pnUtamaHadir.setBackground(new java.awt.Color(255, 255, 255));

        Dhadir.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Dhadir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dhadir.setText("10");

        javax.swing.GroupLayout pnUtamaHadirLayout = new javax.swing.GroupLayout(pnUtamaHadir);
        pnUtamaHadir.setLayout(pnUtamaHadirLayout);
        pnUtamaHadirLayout.setHorizontalGroup(
            pnUtamaHadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnUtamaHadirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dhadir, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnUtamaHadirLayout.setVerticalGroup(
            pnUtamaHadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUtamaHadirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dhadir, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnDasarHadir.add(pnUtamaHadir, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnDasarLayout = new javax.swing.GroupLayout(pnDasar);
        pnDasar.setLayout(pnDasarLayout);
        pnDasarLayout.setHorizontalGroup(
            pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDasarLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(pnDasarTotalGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(52, 52, 52)
                .addComponent(pnDasarHadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(pnDasarTidakHadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        pnDasarLayout.setVerticalGroup(
            pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDasarLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnDasarHadir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnDasarTotalGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnDasarTidakHadir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(327, 327, 327))
        );

        add(pnDasar, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dhadir;
    private javax.swing.JLabel Dtidakhadir;
    private javax.swing.JLabel Dtotalguru;
    private javax.swing.JPanel barAtas;
    private javax.swing.JPanel barAtasHadir;
    private javax.swing.JPanel barAtasTidakHadir;
    private javax.swing.JPanel barAtasTotalGuru;
    private javax.swing.JLabel barTidakHadir;
    private javax.swing.JLabel lbDashboard;
    private javax.swing.JLabel lbHadir;
    private javax.swing.JLabel lbTotalGuru;
    private javax.swing.JPanel pnDasar;
    private javax.swing.JPanel pnDasarHadir;
    private javax.swing.JPanel pnDasarTidakHadir;
    private javax.swing.JPanel pnDasarTotalGuru;
    private javax.swing.JPanel pnUtamaHadir;
    private javax.swing.JPanel pnUtamaTidakHadir;
    private javax.swing.JPanel pnUtamaTotalGuru;
    // End of variables declaration//GEN-END:variables

    private int Dtotalguru() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
