package sipresdik.view;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

public class MainMenu extends javax.swing.JFrame {

    int xx, xy;

    public MainMenu() {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("FlatLaf Error");
        }
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        // Bikin shape rounded semua sudut
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 10, 10));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnKiri = new javax.swing.JPanel();
        lbFotoLogo = new javax.swing.JLabel();
        lbFuelin = new javax.swing.JLabel();
        pnDashboard = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JLabel();
        lgoDashboard = new javax.swing.JLabel();
        pnAbsensi = new javax.swing.JPanel();
        btnAbsensi = new javax.swing.JLabel();
        lgoAbsensi = new javax.swing.JLabel();
        pnRekapAbsensi = new javax.swing.JPanel();
        btnRekapAbsensi = new javax.swing.JLabel();
        lgoRekapAbsensi = new javax.swing.JLabel();
        pnDataGuru = new javax.swing.JPanel();
        btnDataGuru = new javax.swing.JLabel();
        lgoDataGuru = new javax.swing.JLabel();
        pnAbout = new javax.swing.JPanel();
        btnAbout = new javax.swing.JLabel();
        lgoAbout = new javax.swing.JLabel();
        pnLogout = new javax.swing.JPanel();
        btnLogout = new javax.swing.JLabel();
        lgoLogout = new javax.swing.JLabel();
        lbFuelin1 = new javax.swing.JLabel();
        pnManageUser = new javax.swing.JPanel();
        btnManageUser = new javax.swing.JLabel();
        lgoManageUser = new javax.swing.JLabel();
        pnBarAtas = new javax.swing.JPanel();
        pnClose = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        pnMinimize = new javax.swing.JPanel();
        btnMinimize = new javax.swing.JLabel();
        pnKanan = new javax.swing.JPanel();
        pnDasar = new javax.swing.JPanel();
        pnUtama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        pnKiri.setBackground(new java.awt.Color(16, 185, 129));

        lbFotoLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logo_MI.png"))); // NOI18N
        lbFotoLogo.setText("jLabel1");

        lbFuelin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbFuelin.setForeground(new java.awt.Color(255, 255, 255));
        lbFuelin.setText("Absensi");

        pnDashboard.setBackground(new java.awt.Color(16, 185, 129));

        btnDashboard.setBackground(new java.awt.Color(255, 255, 255));
        btnDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setText("Dashboard");
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashboardMouseExited(evt);
            }
        });

        lgoDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lgoDashboard.setForeground(new java.awt.Color(51, 51, 51));
        lgoDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-dashboard-25.png"))); // NOI18N

        javax.swing.GroupLayout pnDashboardLayout = new javax.swing.GroupLayout(pnDashboard);
        pnDashboard.setLayout(pnDashboardLayout);
        pnDashboardLayout.setHorizontalGroup(
            pnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDashboardLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lgoDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDashboardLayout.setVerticalGroup(
            pnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgoDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnAbsensi.setBackground(new java.awt.Color(16, 185, 129));

        btnAbsensi.setBackground(new java.awt.Color(255, 255, 255));
        btnAbsensi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAbsensi.setForeground(new java.awt.Color(255, 255, 255));
        btnAbsensi.setText("Absensi");
        btnAbsensi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAbsensiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAbsensiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAbsensiMouseExited(evt);
            }
        });

        lgoAbsensi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lgoAbsensi.setForeground(new java.awt.Color(51, 51, 51));
        lgoAbsensi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-qr-code-25.png"))); // NOI18N

        javax.swing.GroupLayout pnAbsensiLayout = new javax.swing.GroupLayout(pnAbsensi);
        pnAbsensi.setLayout(pnAbsensiLayout);
        pnAbsensiLayout.setHorizontalGroup(
            pnAbsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAbsensiLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lgoAbsensi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnAbsensiLayout.setVerticalGroup(
            pnAbsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgoAbsensi, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(btnAbsensi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnRekapAbsensi.setBackground(new java.awt.Color(16, 185, 129));

        btnRekapAbsensi.setBackground(new java.awt.Color(255, 255, 255));
        btnRekapAbsensi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRekapAbsensi.setForeground(new java.awt.Color(255, 255, 255));
        btnRekapAbsensi.setText("Rekap Absensi");
        btnRekapAbsensi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRekapAbsensiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRekapAbsensiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRekapAbsensiMouseExited(evt);
            }
        });

        lgoRekapAbsensi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lgoRekapAbsensi.setForeground(new java.awt.Color(51, 51, 51));
        lgoRekapAbsensi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-report-25.png"))); // NOI18N

        javax.swing.GroupLayout pnRekapAbsensiLayout = new javax.swing.GroupLayout(pnRekapAbsensi);
        pnRekapAbsensi.setLayout(pnRekapAbsensiLayout);
        pnRekapAbsensiLayout.setHorizontalGroup(
            pnRekapAbsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRekapAbsensiLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lgoRekapAbsensi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRekapAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnRekapAbsensiLayout.setVerticalGroup(
            pnRekapAbsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgoRekapAbsensi, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(btnRekapAbsensi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnDataGuru.setBackground(new java.awt.Color(16, 185, 129));

        btnDataGuru.setBackground(new java.awt.Color(255, 255, 255));
        btnDataGuru.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDataGuru.setForeground(new java.awt.Color(255, 255, 255));
        btnDataGuru.setText("Data Guru");
        btnDataGuru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDataGuruMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDataGuruMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDataGuruMouseExited(evt);
            }
        });

        lgoDataGuru.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lgoDataGuru.setForeground(new java.awt.Color(51, 51, 51));
        lgoDataGuru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-teacher-25.png"))); // NOI18N

        javax.swing.GroupLayout pnDataGuruLayout = new javax.swing.GroupLayout(pnDataGuru);
        pnDataGuru.setLayout(pnDataGuruLayout);
        pnDataGuruLayout.setHorizontalGroup(
            pnDataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDataGuruLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lgoDataGuru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDataGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnDataGuruLayout.setVerticalGroup(
            pnDataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgoDataGuru, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(btnDataGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnAbout.setBackground(new java.awt.Color(16, 185, 129));

        btnAbout.setBackground(new java.awt.Color(255, 255, 255));
        btnAbout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAbout.setForeground(new java.awt.Color(255, 255, 255));
        btnAbout.setText("About");
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAboutMouseExited(evt);
            }
        });

        lgoAbout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lgoAbout.setForeground(new java.awt.Color(51, 51, 51));
        lgoAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-about-25.png"))); // NOI18N

        javax.swing.GroupLayout pnAboutLayout = new javax.swing.GroupLayout(pnAbout);
        pnAbout.setLayout(pnAboutLayout);
        pnAboutLayout.setHorizontalGroup(
            pnAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAboutLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lgoAbout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnAboutLayout.setVerticalGroup(
            pnAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgoAbout, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(btnAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnLogout.setBackground(new java.awt.Color(16, 185, 129));

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });

        lgoLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lgoLogout.setForeground(new java.awt.Color(51, 51, 51));
        lgoLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-logout-25.png"))); // NOI18N

        javax.swing.GroupLayout pnLogoutLayout = new javax.swing.GroupLayout(pnLogout);
        pnLogout.setLayout(pnLogoutLayout);
        pnLogoutLayout.setHorizontalGroup(
            pnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLogoutLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lgoLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnLogoutLayout.setVerticalGroup(
            pnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgoLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lbFuelin1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbFuelin1.setForeground(new java.awt.Color(255, 255, 255));
        lbFuelin1.setText("Guru");

        pnManageUser.setBackground(new java.awt.Color(16, 185, 129));

        btnManageUser.setBackground(new java.awt.Color(255, 255, 255));
        btnManageUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManageUser.setForeground(new java.awt.Color(255, 255, 255));
        btnManageUser.setText("Manajemen User");
        btnManageUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManageUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageUserMouseExited(evt);
            }
        });

        lgoManageUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lgoManageUser.setForeground(new java.awt.Color(51, 51, 51));
        lgoManageUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-user-management-25.png"))); // NOI18N

        javax.swing.GroupLayout pnManageUserLayout = new javax.swing.GroupLayout(pnManageUser);
        pnManageUser.setLayout(pnManageUserLayout);
        pnManageUserLayout.setHorizontalGroup(
            pnManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnManageUserLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lgoManageUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnManageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnManageUserLayout.setVerticalGroup(
            pnManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgoManageUser, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(btnManageUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnKiriLayout = new javax.swing.GroupLayout(pnKiri);
        pnKiri.setLayout(pnKiriLayout);
        pnKiriLayout.setHorizontalGroup(
            pnKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKiriLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbFotoLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbFuelin1)
                    .addComponent(lbFuelin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnAbsensi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnRekapAbsensi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnDataGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnManageUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnKiriLayout.setVerticalGroup(
            pnKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKiriLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbFotoLogo)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnKiriLayout.createSequentialGroup()
                        .addComponent(lbFuelin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(lbFuelin1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(pnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnDataGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnRekapAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnManageUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        getContentPane().add(pnKiri, java.awt.BorderLayout.LINE_START);

        pnBarAtas.setPreferredSize(new java.awt.Dimension(865, 25));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-close-20.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnCloseLayout = new javax.swing.GroupLayout(pnClose);
        pnClose.setLayout(pnCloseLayout);
        pnCloseLayout.setHorizontalGroup(
            pnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCloseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnCloseLayout.setVerticalGroup(
            pnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCloseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-minimize-20.png"))); // NOI18N
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnMinimizeLayout = new javax.swing.GroupLayout(pnMinimize);
        pnMinimize.setLayout(pnMinimizeLayout);
        pnMinimizeLayout.setHorizontalGroup(
            pnMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMinimizeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnMinimizeLayout.setVerticalGroup(
            pnMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMinimize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnBarAtasLayout = new javax.swing.GroupLayout(pnBarAtas);
        pnBarAtas.setLayout(pnBarAtasLayout);
        pnBarAtasLayout.setHorizontalGroup(
            pnBarAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBarAtasLayout.createSequentialGroup()
                .addContainerGap(814, Short.MAX_VALUE)
                .addComponent(pnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnBarAtasLayout.setVerticalGroup(
            pnBarAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBarAtasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnBarAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(pnBarAtas, java.awt.BorderLayout.PAGE_START);

        pnKanan.setLayout(new java.awt.BorderLayout());

        pnDasar.setBackground(new java.awt.Color(255, 255, 255));

        pnUtama.setBackground(new java.awt.Color(255, 255, 255));
        pnUtama.setForeground(new java.awt.Color(255, 255, 255));
        pnUtama.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout pnDasarLayout = new javax.swing.GroupLayout(pnDasar);
        pnDasar.setLayout(pnDasarLayout);
        pnDasarLayout.setHorizontalGroup(
            pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDasarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        pnDasarLayout.setVerticalGroup(
            pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDasarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        pnKanan.add(pnDasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnKanan, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        pnClose.setBackground(new Color(255, 0, 0));
        dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        pnClose.setBackground(new Color(255, 0, 0));
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        pnClose.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_btnCloseMouseExited

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        pnMinimize.setBackground(new Color(204, 204, 204));
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        pnMinimize.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        pnMinimize.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_btnMinimizeMouseExited

    private void btnDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseEntered
        pnDashboard.setBackground(new Color(12,175,121));
    }//GEN-LAST:event_btnDashboardMouseEntered

    private void btnDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseExited
        pnDashboard.setBackground(new Color(16, 185, 129));
    }//GEN-LAST:event_btnDashboardMouseExited

    private void btnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseClicked
        pnDashboard.setBackground(new Color(12, 175, 121));
        pnUtama.removeAll();
        pnUtama.add(new Dashboard());
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_btnDashboardMouseClicked

    private void btnAbsensiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbsensiMouseClicked
        pnAbsensi.setBackground(new Color(12, 175, 121));
        pnUtama.removeAll();
        pnUtama.add(new Presensi());
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_btnAbsensiMouseClicked

    private void btnAbsensiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbsensiMouseEntered
        pnAbsensi.setBackground(new Color(12,175,121));
    }//GEN-LAST:event_btnAbsensiMouseEntered

    private void btnAbsensiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbsensiMouseExited
        pnAbsensi.setBackground(new Color(16, 185, 129));
    }//GEN-LAST:event_btnAbsensiMouseExited

    private void btnRekapAbsensiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRekapAbsensiMouseClicked
        pnRekapAbsensi.setBackground(new Color(12, 175, 121));
        pnUtama.removeAll();
        pnUtama.add(new RekapPresensi());
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_btnRekapAbsensiMouseClicked

    private void btnRekapAbsensiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRekapAbsensiMouseEntered
        pnRekapAbsensi.setBackground(new Color(12,175,121));
    }//GEN-LAST:event_btnRekapAbsensiMouseEntered

    private void btnRekapAbsensiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRekapAbsensiMouseExited
        pnRekapAbsensi.setBackground(new Color(16, 185, 129));
    }//GEN-LAST:event_btnRekapAbsensiMouseExited

    private void btnDataGuruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataGuruMouseClicked
        pnDataGuru.setBackground(new Color(12, 175, 121));
        pnUtama.removeAll();
        pnUtama.add(new DataGuru());
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_btnDataGuruMouseClicked

    private void btnDataGuruMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataGuruMouseEntered
        pnDataGuru.setBackground(new Color(12,175,121));
    }//GEN-LAST:event_btnDataGuruMouseEntered

    private void btnDataGuruMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataGuruMouseExited
        pnDataGuru.setBackground(new Color(16, 185, 129));
    }//GEN-LAST:event_btnDataGuruMouseExited

    private void btnAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseClicked
        pnAbout.setBackground(new Color(12, 175, 121));
        String aboutAbsensi = """
    ==============================
                     About SIPRESDIK
    ==============================
Nama Aplikasi     : ABSENSI GURU MI NURUL HUDA III
Versi                    : 1.0.0
Dibuat oleh         : TIM 4 SI 2024 INSTITUT TEKNOLOGI MOJOSARI
Tanggal Rilis        : 01 Oktober 2025

Deskripsi:


Kontak Bantuan :
Email : miftakhurozaq123@gmail.com
WhatsApp : 085655873785

Terima kasih....!
    """;

        JOptionPane.showMessageDialog(null, aboutAbsensi, "Tentang Aplikasi Absensi Guru", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnAboutMouseClicked

    private void btnAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseEntered
        pnAbout.setBackground(new Color(12,175,121));
    }//GEN-LAST:event_btnAboutMouseEntered

    private void btnAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseExited
        pnAbout.setBackground(new Color(16, 185, 129));
    }//GEN-LAST:event_btnAboutMouseExited

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        int response = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar?",
                "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);

        if (response == JOptionPane.YES_OPTION) {
            // Jika Yes, kembali ke login
//            new FormLogin().setVisible(true);
            dispose(); // Menutup jendela saat ini
        } else if (response == JOptionPane.NO_OPTION) {
            // Jika No, kembali ke menu terakhir yang dibuka 
            // Misalnya, membuka kembali JFrame menu terakhir
            this.setVisible(true); // Menampilkan kembali menu yang sedang aktif
        }
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        pnLogout.setBackground(new Color(12,175,121));
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        pnLogout.setBackground(new Color(16, 185, 129));
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnManageUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageUserMouseClicked
        pnManageUser.setBackground(new Color(12, 175, 121));
        pnUtama.removeAll();
        pnUtama.add(new ManajemenUser());
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_btnManageUserMouseClicked

    private void btnManageUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageUserMouseEntered
        pnManageUser.setBackground(new Color(12,175,121));
    }//GEN-LAST:event_btnManageUserMouseEntered

    private void btnManageUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageUserMouseExited
        pnManageUser.setBackground(new Color(16, 185, 129));
    }//GEN-LAST:event_btnManageUserMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAbout;
    private javax.swing.JLabel btnAbsensi;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnDashboard;
    private javax.swing.JLabel btnDataGuru;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnManageUser;
    private javax.swing.JLabel btnMinimize;
    private javax.swing.JLabel btnRekapAbsensi;
    private javax.swing.JLabel lbFotoLogo;
    private javax.swing.JLabel lbFuelin;
    private javax.swing.JLabel lbFuelin1;
    private javax.swing.JLabel lgoAbout;
    private javax.swing.JLabel lgoAbsensi;
    private javax.swing.JLabel lgoDashboard;
    private javax.swing.JLabel lgoDataGuru;
    private javax.swing.JLabel lgoLogout;
    private javax.swing.JLabel lgoManageUser;
    private javax.swing.JLabel lgoRekapAbsensi;
    private javax.swing.JPanel pnAbout;
    private javax.swing.JPanel pnAbsensi;
    private javax.swing.JPanel pnBarAtas;
    private javax.swing.JPanel pnClose;
    private javax.swing.JPanel pnDasar;
    private javax.swing.JPanel pnDashboard;
    private javax.swing.JPanel pnDataGuru;
    private javax.swing.JPanel pnKanan;
    private javax.swing.JPanel pnKiri;
    private javax.swing.JPanel pnLogout;
    private javax.swing.JPanel pnManageUser;
    private javax.swing.JPanel pnMinimize;
    private javax.swing.JPanel pnRekapAbsensi;
    private javax.swing.JPanel pnUtama;
    // End of variables declaration//GEN-END:variables
}
