package sipresdik.view;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;

/**
 *
 * @author HP
 */
public class Presensi extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Presensi() {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("FlatLaf Error");
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barAtas = new javax.swing.JPanel();
        lbAbsensi = new javax.swing.JLabel();
        pnDasar = new javax.swing.JPanel();
        lbDataAbsensi = new javax.swing.JLabel();
        lbJamMasukJamPulang = new javax.swing.JLabel();
        tbAbsensi = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtScan = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        barAtas.setBackground(new java.awt.Color(16, 185, 129));

        lbAbsensi.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        lbAbsensi.setForeground(new java.awt.Color(255, 255, 255));
        lbAbsensi.setText("Absensi");

        javax.swing.GroupLayout barAtasLayout = new javax.swing.GroupLayout(barAtas);
        barAtas.setLayout(barAtasLayout);
        barAtasLayout.setHorizontalGroup(
            barAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barAtasLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lbAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(519, Short.MAX_VALUE))
        );
        barAtasLayout.setVerticalGroup(
            barAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbAbsensi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(barAtas, java.awt.BorderLayout.PAGE_START);

        lbDataAbsensi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbDataAbsensi.setText("Data Absensi Masuk Hari Ini");

        lbJamMasukJamPulang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbJamMasukJamPulang.setText("Jam Masuk : 07 : 00 : 00 | Jam Pulang : 10 : 30 : 00");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbAbsensi.setViewportView(jTable1);

        javax.swing.GroupLayout pnDasarLayout = new javax.swing.GroupLayout(pnDasar);
        pnDasar.setLayout(pnDasarLayout);
        pnDasarLayout.setHorizontalGroup(
            pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDasarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbJamMasukJamPulang, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
            .addGroup(pnDasarLayout.createSequentialGroup()
                .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDasarLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(lbDataAbsensi))
                    .addGroup(pnDasarLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tbAbsensi, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                            .addComponent(txtScan))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnDasarLayout.setVerticalGroup(
            pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDasarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbDataAbsensi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbJamMasukJamPulang)
                .addGap(18, 18, 18)
                .addComponent(tbAbsensi, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(txtScan, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnDasar, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barAtas;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbAbsensi;
    private javax.swing.JLabel lbDataAbsensi;
    private javax.swing.JLabel lbJamMasukJamPulang;
    private javax.swing.JPanel pnDasar;
    private javax.swing.JScrollPane tbAbsensi;
    private javax.swing.JTextField txtScan;
    // End of variables declaration//GEN-END:variables
}
